import { Suspense } from 'react';
import { AppContextProvider } from './context/AppContext';
import './global.css';
import Loading from './components/Loading';
import BookHeader from './components/BookHeader';

export const metadata = {
  title: 'Welcome to assignment-5',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppContextProvider>
          <Suspense fallback={<Loading />}>
            <Loading />
            <div className="flex flex-col min-h-screen bg-[#f7f8fa]">
              <div>
                <BookHeader />
              </div>
              <div className="flex-1 p-3">{children}</div>
            </div>
          </Suspense>
        </AppContextProvider>
      </body>
    </html>
  );
}
